### ISSUE TITLE
chunk size needed or not

### ISSUE THREAD

**Issue by mrfragger** [GhostNaN/whisper-subs#3]
I just set chunk size  to 99999 cuz when I tried 15 or 30 I had overlapping subs
meaning the timecodes would overlap.  So one sub line would remain for a couple seconds while the next sub line would show.

Anyway now it works just fine. I get the idea...myself I split 50+ hour audiobooks into 200 chunks of audio them recombined the whisper.cpp generated subs into one sub.

Only modifications I had to make were to change all srt to vtt, set max length to 60 and split on word and set a prompt.
	os.execute(WHISPER_CMD..' -ml 60 -sow --prompt "The beef was delicious; I had seconds, thirds, fourths and fifths!" --output-vtt -d '..CHUNK_SIZE..' -f '..TMP_WAV_PATH..' -of '..TMP_SUB_PATH..'_append', 'r')

and 
local WHISPER_CMD = "~/whisper/whisper.cpp-1.6.2/./main -m ~/whisper/whisper.cpp-1.6.2/models/ggml-medium.en.bin --threads 8 --language en"

and
local CHUNK_SIZE = 999999 * 1000 -- the amount of subs to process at a time in ms

I know the max length is around 34 or 36 hours...forgot but for this script usually would just do chunks under 15 mins I'd imagine.

**Comment by GhostNaN** [comment]
> I just set chunk size to 99999 cuz when I tried 15 or 30 I had overlapping subs
meaning the timecodes would overlap. So one sub line would remain for a couple seconds while the next sub line would show.

I'm aware and I'm sure there is a possible solution for this.
I imagine it would be some kind of complicated "compare and delete extra"
But I don't really have the motivation now to implement something like that.
As for why I left the behavior in, I already explained in the README about this:

Also modifying the CHUNK_SIZE is a good idea. This will always be a balancing act. Because how whisper works, sometimes when music is playing whisper will just give up at creating more subtitles. But, this behavior is only until the end of the process chunk. What this means is that having a lower CHUNK_SIZE will lead to less of this terrible whisper behavior. Although if the CHUNK_SIZE is too low the model won't be able to keep up AND the subs will overlap a lot more. A CHUNK_SIZE too large will lead to slow first initial subtitles creation and the previous "whisper giving up" behavior for a longer period of time.


Anyways, use this script however you wish.
The whole point of this script is to produce subtitles in "chunks".
The reason for this is that it's much faster to create subtitles in 15 second "chunks" and appending as you go.
As if a train was laying out it's own tracks in front of itself.
That is.. as long as your computer is fast enough to process the subtitles faster than you can watch/listen.
Rather than waiting for whisper.cpp to process the entire video/audio.

> Only modifications I had to make were to change all srt to vtt, set max length to 60 and split on word and set a prompt.
os.execute(WHISPER_CMD..' -ml 60 -sow --prompt "The beef was delicious; I had seconds, thirds, fourths and fifths!" --output-vtt -d '..CHUNK_SIZE..' -f '..TMP_WAV_PATH..' -of '..TMP_SUB_PATH..'_append', 'r')

You didn't need to put all that stuff in ```os.execute``` that's what ```WHISPER_CMD``` is for...
But you did have to modify the code to get VTT output instead, I preferred SRT so I just coded for it.

I'm closing the issue as I think I answered your question.

**Comment by mrfragger** [comment]
ok I avoided large-v3 like a plague cuz of reports of hallucination...so far the turbo is working good.  I liked distil-large-v3 but it was only English and did like six times knight instead of night...got 6x to 8x realtime speed on Mac M1.  For large-v3-turbo get about 5.7x realtime speed so it's pretty decent.  Can't do translation to English but can do multiple languages at a time. This is now what I use.  Think I'll use it for video / audio content under 30 mins or so.  Anything longer will use my regular script.  Thanks a bunch for your script ..it's quite convenient.

local WHISPER_CMD = "~/whisper/whisper.cpp-1.7.1/./main -m ~/whisper/whisper.cpp-1.7.1/models/ggml-large-v3-turbo.bin --threads 8 --language english -fa -ml 88 -sow --prompt '“It’s your fault! You should exercise more, but you aren’t doing it. Shame on you!”' I am here to say: It isn’t your fault."
local CHUNK_SIZE = 99999 * 1000 -- the amount of subs to process at a time in ms


think I can ditch all the models and just stick with large-v3-turbo

<img width="505" alt="image" src="https://github.com/user-attachments/assets/f732f15e-0881-45b7-b120-54d33991d540">

whisper.cpp took 00h:01m:22s
Transcription took 82 seconds

Transcription  started at 2024_10_18_19:03:22
Transcription finished at 2024_10_18_19:04:44

Total duration of audiobook is 00h:07m:57s
Total duration of audiobook is 477 seconds

Whisper large-v3-turbo model transcribed at 5.82x realtime speed
Set language: en | Translated: 
Max length: 88 | Print Colors: -pc
No Graphics:  | Flash Attention: -fa
--prompt: “It’s your fault! You should exercise more, but you aren’t doing it. Shame on you!” I am here to say: It isn’t your fault.
